[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opentelemetry-instrumentation-circuits"
dynamic = ["version"]
description = "OpenTelemetry circuits instrumentation"
readme = "README.rst"
license = "Apache-2.0"
authors = [
  { name = "OpenTelemetry Authors", email = "cncf-opentelemetry-contributors@lists.cncf.io" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "opentelemetry-api ~= 1.12",
  "opentelemetry-instrumentation == 0.41b0.dev",
  "wrapt >= 1.0.0, < 2.0.0",
]

[project.optional-dependencies]
instruments = [
  "circuits >= 3.2, < 4.0",
]
test = [
  "opentelemetry-instrumentation-circuits[instruments]",
  "markupsafe==2.0.1",
  "opentelemetry-test-utils == 0.41b0.dev",
]

[project.entry-points.opentelemetry_instrumentor]
circuits = "opentelemetry.instrumentation.circuits:CircuitsInstrumentor"

[project.urls]
Homepage = "https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-circuits"

[tool.hatch.version]
path = "src/opentelemetry/instrumentation/circuits/version.py"

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/tests",
]

[tool.hatch.build.targets.wheel]
packages = ["src/opentelemetry"]
